/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffffff",
        "on-primary-fixed-variant": "#454747",
        "primary": "#ffffff",
        "on-error": "#690005",
        "surface-container-highest": "#353535",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#c6c6c7",
        "surface-bright": "#393939",
        "outline-variant": "#444748",
        "outline": "#8e9192",
        "on-primary-container": "#636565",
        "on-error-container": "#ffdad6",
        "secondary-container": "#4a4949",
        "on-primary-fixed": "#1a1c1c",
        "on-primary": "#2f3131",
        "secondary-fixed-dim": "#c9c6c5",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e4e2e1",
        "on-tertiary-fixed-variant": "#474746",
        "primary-container": "#e2e2e2",
        "surface-variant": "#353535",
        "on-secondary": "#313030",
        "surface-container": "#20201f",
        "on-secondary-fixed": "#1c1b1b",
        "error-container": "#93000a",
        "tertiary-container": "#e4e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#656464",
        "on-secondary-container": "#bab8b7",
        "background": "#131313",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "secondary": "#c9c6c5",
        "on-tertiary": "#303030",
        "surface": "#131313",
        "primary-fixed": "#e2e2e2",
        "inverse-primary": "#5d5f5f",
        "inverse-on-surface": "#313030",
        "surface-tint": "#c6c6c7",
        "inverse-surface": "#e5e2e1",
        "success-muted": "#1b2b1b",
        "on-success-muted": "#81c784",
        "brand-accent": "#B4E3AC"
      },
      spacing: {
        "unit": "4px", "gutter": "16px", "xs": "4px", "xl": "40px", "lg": "24px", "md": "16px", "margin-desktop": "48px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"], 
        "body-lg": ["Geist", "sans-serif"], 
        "body-md": ["Geist", "sans-serif"], 
        "headline-md": ["Geist", "sans-serif"],
        "mono": ["Geist Mono", "monospace"],
        "display": ["Geist Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-sm": ["10px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }]
      },
      borderRadius: {
        'none': '0px',
        'sm': '0px',
        DEFAULT: '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px', // for rounded pills/avatars if needed
      }
    },
  },
  plugins: [],
}
